name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Print GITHUB_TOKEN to confirm it's available
      - name: Print GITHUB_TOKEN
        run: |
          echo "GITHUB_TOKEN is available"
          echo "Token value: ${{ secrets.GITHUB_TOKEN }}"  # Token will be masked in the logs
          
      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Set Git user name and email
      - name: Set Git user name and email
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Set up GitHub token for authentication
      - name: Set up GitHub token for authentication
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        
      # List files in the root directory
      - name: List files in root directory
        run: |
          echo "Listing files in the root directory:"
          ls -la   
        env:
          CI: false  # Disable the default CI behavior
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass the GitHub token for authentication
